File = _{ SOI ~ TopLevel ~ EOI }

WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT = _{ DOCUMENTATION_COMMENT | SINGLE_LINE_COMMENT | MULTI_LINE_COMMENT }
SINGLE_LINE_COMMENT = { "//" ~ (!NEWLINE ~ ANY)* }
MULTI_LINE_COMMENT = { "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
DOCUMENTATION_COMMENT = { ("///" ~ (!NEWLINE ~ ANY)*)+ }

Integer = @{
	("0b" ~ ASCII_BIN_DIGIT+) |
	("0o" ~ ASCII_OCT_DIGIT+) |
    ("0x" ~ ASCII_HEX_DIGIT+) |
    (ASCII_DIGIT+)
}

ScopeStart = _{ ("{" ~ PUSH_LITERAL("}")) | ("[" ~ PUSH_LITERAL("]")) }
ScopeEnd = _{ POP }

Identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
Module = ${ Identifier ~ ("::" ~ Identifier)* }

Type = { ArrayType | PointerType | FunctionType | NamedType }
ArrayType = { "arr" ~ #count = Integer ~ #type = Type }
PointerType = { "ptr" ~ #type = Type }
FunctionType = { "fn" ~ #callconv = FunctionCallConv ~ #generics = FunctionGenerics ~ "(" ~ #args = FunctionArgs ~ ")" ~ #ret = FunctionRet }
FunctionCallConv = { #name = Identifier? }
FunctionGenerics = { #generic_params = GenericParams? }
FunctionArgs = { (Binding ~ ("," ~ Binding)*)? }
FunctionRet = { ("->" ~ #type = Type)? }
NamedType = { #name = Module ~ #generic_args = GenericArgs? }

Binding = { #name = Identifier ~ ":" ~ #type = Type }
TypedBlock = { #type = Type ~ #block = Block }
GenericParams = { "<" ~ Identifier ~ ("," ~ Identifier)* ~ ">" }
GenericArgs = { "<" ~ Type ~ ("," ~ Type)* ~ ">" }
GenericMatch = { "<" ~ GenericMatchArm ~ ("," ~ GenericMatchArm)* ~ ">" }
GenericMatchArm = { #pattern = GenericMatchPattern ~ "=>" ~ #expr = GenericMatchExpr }
GenericMatchPattern = { (Type | ("(" ~ Type ~ ("," ~ Type)* ~ ")")) }
GenericMatchExpr = { RelationRight | RelationBlockRight }

TopLevel = _{ #mod = Mod? ~ #uses = Uses ~ #top_blocks = TopBlocks }
Uses = { Use* }
TopBlocks = { RelationBlock* }

Mod = { "mod" ~ #module = Module }
Use = { "use" ~ #module = Module }

Relation = { #left = RelationLeft ~ "=" ~ #right = RelationRight }
RelationLeft = { #value = (Integer | Identifier) ~ #generic_args = GenericArgs? }
RelationRight = { TypedBlock | Binding | Relation | Integer | Identifier | GenericMatch }

RelationBlock = { #left = RelationBlockLeft ~ #right = RelationBlockRight }
RelationBlockLeft = { #kind = Identifier ~ (#name = Identifier ~ #generic_params = GenericParams?)? ~ #generic_args = GenericArgs? }
RelationBlockRight = { Block | GenericMatch }

Block = { ScopeStart ~ BlockItems ~ ScopeEnd }
BlockItems = _{ (Item ~ Comma?)* }
Item = _{ Relation | RelationBlock }
Comma = { "," }
